---
- name: HOSTNAME | Getting facts
  setup:
    filter: ansible_*

- name: HOSTNAME | Set hostname
  include_tasks: bootstrap-hostname.yml
  when: override_system_hostname|default(false)

- name: HOSTNAME | /etc/hosts file preparation
  include_tasks: bootstrap-hosts.yml
  when: override_file_hosts|default(false)
