---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: Ubuntu18.04
    box: ubuntu/bionic64
#  - name: Ubuntu16.04
#    box: ubuntu/xenial64
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: ubuntu
verifier:
  name: testinfra
  lint:
    name: flake8
