---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: Ubuntu18.04
    image: ubuntu:18.04
  - name: Ubuntu16.04
    image: ubuntu:16.04
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: ubuntu
verifier:
  name: testinfra
  lint:
    name: flake8
